### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [romariocarvalhoneto/BHCgeo#1]
#Problem

Please fix the issue tracker so that it directs to the GitHub issue page

**Comment by romariocarvalhoneto** [comment]
You mean change the tracker address to this issue page, at the metadata.txt file? If it is that, it's done.

**Comment by NyakudyaA** [comment]
HI It is not yet fixed, Did you upload a new plugin with this fix. Because if I click on the Issue link it redirects me to the code repository not the https://github.com/romariocarvalhoneto/BHCgeo/issues

**Comment by romariocarvalhoneto** [comment]
Ok. I think now it's done right.

**Comment by romariocarvalhoneto** [comment]
Ok. I've just changed. I hope now it is working fine.

Em ter, 2 de jul de 2019 às 05:12, mazano <notifications@github.com>
escreveu:

**Comment by pcav** [comment]
Fixed
