### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [romariocarvalhoneto/BHCgeo#2]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by romariocarvalhoneto** [comment]
I don't think we have .pyc files. I just checked. Which other file would be unnecessary?

**Comment by pcav** [comment]
https://github.com/romariocarvalhoneto/BHCgeo/tree/master/bhcgeoqgis/__pycache__

cheers

**Comment by romariocarvalhoneto** [comment]
Thanks. I'm new into github and I think I delete it correctly. I've created a new branch called "delete unnecessary" and deleted all the files in that __pycache__ folder. Is that correct?

**Comment by pcav** [comment]
I don't think you need a separate branch, you can delete in master

**Comment by romariocarvalhoneto** [comment]
OK. Deleted __pycache__ in master.
